### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by probonopd** [TheFutureShell/updatedeployqt#1]
```
From the below options , select the bridge you want to use:
1. AppImageUpdater - Used to deploy updater for Qt Application packaged with AppImage.
2. QInstaller      - Used to deploy updater for Qt Installer Framework.
3. Github Releases - Used to deploy updater for Qt Application released on Github.
```

What do I need to select if I want to deploy updater for Qt Application packaged with AppImage  released on GitHub? I can't select both 1 and 3...

**Comment by antony-jr** [comment]
you just need to enter **1** as a integer.

**Comment by probonopd** [comment]
> Please enter the QObject name of the QMenu you want to integrate: 

How do I find this out? Is there a tool that can give me the QObject name for an already-compiled application?

**Comment by probonopd** [comment]
> you just need to enter 1 as a integer.

In which case would I have to select 3?

**Comment by antony-jr** [comment]
> How do I find this out? Is there a tool that can give me the QObject name for an already-compiled application?

That is the catch , if you want to attach the updater to menu bar option then you have to know it. Auto update does not require this. You can get the name from **ui** files or the source files , but as the developer you can just tell.  **As I said , We can also look for QMenuBar if all fails , I'm still working on it**. For now you can look into the source files and look for **QMenu** object that sets the object name using ```setObjectName()``` method. Typically they are set as **menuHelp** if the menu option name is **help** or **menuAbout** if the menu option name is **About** and so on.



> In which case would I have to select 3?

When you don't use AppImages or Qt Installer Framework and just releasing your software via Github by unknown means.

**Comment by probonopd** [comment]
> When you don't use AppImages or Qt Installer Framework and just releasing your software via Github by unknown means.

Ah, maybe you could add "e.g., .tar.gz, .zip" or something like that in the description, that would make it more clear.

**Comment by antony-jr** [comment]
> Ah, maybe you could add "e.g., .tar.gz, .zip" or something like that in the description, that would make it more clear.

Well it is meant for checking updates from Github only. I think I should just drop it maybe. Because the updater has all the cases covered. AppImages for Linux. Qt Installer Framework for Windows and MacOSX and even Linux.
