### ISSUE TITLE
Bundle lib%sBridge.so and libqxcb.so in the updatedeployqt AppImage

### ISSUE THREAD

**Issue by probonopd** [TheFutureShell/updatedeployqt#6]
Please bundle all versions of `lib%sBridge.so` and `libqxcb`.so in the `updatedeployqt AppImage` rather than downloading them at runtime. Some build systems (e.g., https://build.opensuse.org/) do not allow accessing the internet at AppImage build time. So the current solution would not work there at all.

**Comment by antony-jr** [comment]
This was a good decision, The binary size is now only **600 KiB**(appox.), libcurl was really heavy. Anyways now ```updatedeployqt``` does not require network on runtime.
