### ISSUE TITLE
It takes a while before the additional menu entry appears

### ISSUE THREAD

**Issue by probonopd** [TheFutureShell/updatedeployqt#8]
It takes a while before the additional menu entry appears, presumably due to

```
QtPluginInjector:: INFO: comparing hashed( "ec2d5e217d492a6e7151dbc387332866" ) == required( "ec2d5e217d492a6e7151dbc387332866" )
QtPluginInjector:: INFO: mdsum matched.
```

What is being hashed and for what reason? Could the hashing be done at a later point in time?

**Comment by antony-jr** [comment]
The delay is intended, For now we have 4 seconds delay. This is to wait for the application to start, if the application does not start in 4 seconds then we wait for another 4 seconds. The construction of QApplication object implies that the application has started. The MD5 hash is the only way we could load the intended plugin which is targeted by the Qt Plugin Injector. Without the hash we would have to search blindly which is not good.

**Comment by probonopd** [comment]
> The delay is intended, For now we have 4 seconds delay. This is to wait for the application to start

Makes sense...
